# Generated by Django 2.2.18 on 2021-02-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pix',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pix.Category'),
        ),
    ]
